name: deploy

on:
  workflow_dispatch:
  repository_dispatch: 
    types: [cron_deploy,manual_deploy]
  push: 
    branches: 
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    env:
      DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
      GAS_URL: ${{secrets.GAS_URL_PREVIEW}}
      GAS_TOKEN: ${{secrets.GAS_TOKEN}}

    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile
      
      - name: build
        run: pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        if: ${{github.event_name !='workflow_dispatch'||github.ref_name=='main'}}
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=polaris-consts
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web

      - name: Publish to Cloudflare Pages Preview
        uses: cloudflare/wrangler-action@v3
        if: ${{github.event_name =='workflow_dispatch'&&github.ref_name!='main'}}
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=polaris-consts --branch=${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web

      - name: success notify
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          color: 0x00FF00
          title: deploy success
          nodetail: true

      - name: error notify
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          content: "<@1111261400157929482>"
          color: 0xFF0000
          title: actions error
          noprefix: true