name: deploy

on:
  workflow_dispatch:
  push: 
    branches: 
      - main
  schedule: 
    # 毎日0:15
    - cron: "15 15 * * *"

env:
  DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      GAS_URL: ${{secrets.GAS_URL}}
      BUILD_CODE: 0

    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: start notify
        uses: sarisia/actions-status-discord@v1
        with:
          color: 0x0000FF
          title: start deploy
          nodetail: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile
      
      - name: build
        run: pnpm run build || echo "BUILD_CODE=$?" >> $GITHUB_ENV
        if: github.event_name == 'schedule'
      
        #スケジュール実行以外の時は強制ビルド 
      - name: build force
        run: pnpm run build || echo "BUILD_CODE=$?" >> $GITHUB_ENV
        if: github.event_name != 'schedule'
        env: 
          FORCE: 1

      - name: skip deploy notify
        if: env.BUILD_CODE==11
        uses: sarisia/actions-status-discord@v1
        with:
          color: 0xFFFF00
          title: deploy skipped
          nodetail: true
      
      - name: build error
        if: env.BUILD_CODE!=0&&env.BUILD_CODE!=11
        run: exit 1

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        if: ${{env.BUILD_CODE==0}}
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=polaris-consts
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web

      - name: success notify
        if: ${{env.BUILD_CODE==0}}
        uses: sarisia/actions-status-discord@v1
        with:
          color: 0x00FF00
          title: deploy success
          nodetail: true

      - name: error notify
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          content: "error! <@1111261400157929482>"
          color: 0xFF0000
          title: actions error
          noprefix: true